MODULE field_dof_utils

   USE global, ONLY: NNODES, FIELD_DOF_COUNT, NODE_TO_FIELD_DOF
   USE screen, ONLY: ERROR_ABORT

   IMPLICIT NONE

   PUBLIC :: REDUCE_FIELD_ARRAY, EXPAND_FIELD_ARRAY, MAP_FIELD_NODE

CONTAINS

   SUBROUTINE MAP_FIELD_NODE(NODE, FIELD_DOF)

      INTEGER, INTENT(IN) :: NODE
      INTEGER, INTENT(OUT) :: FIELD_DOF

      IF (.NOT. ALLOCATED(NODE_TO_FIELD_DOF)) &
         CALL ERROR_ABORT('Field DOF mapping is not allocated.')
      IF (NODE < 0 .OR. NODE >= NNODES) &
         CALL ERROR_ABORT('Geometry node is outside the field DOF mapping.')

      FIELD_DOF = NODE_TO_FIELD_DOF(NODE)
      IF (FIELD_DOF < 0 .OR. FIELD_DOF >= FIELD_DOF_COUNT) &
         CALL ERROR_ABORT('Field DOF mapping contains an invalid compressed index.')

   END SUBROUTINE MAP_FIELD_NODE


   SUBROUTINE REDUCE_FIELD_ARRAY(FULL_VALUES, REDUCED_VALUES)

      REAL(KIND=8), DIMENSION(0:), INTENT(IN) :: FULL_VALUES
      REAL(KIND=8), DIMENSION(0:), INTENT(OUT) :: REDUCED_VALUES
      INTEGER :: NODE, FIELD_DOF

      IF (SIZE(FULL_VALUES) /= NNODES) &
         CALL ERROR_ABORT('Full field array size does not match NNODES.')
      IF (SIZE(REDUCED_VALUES) /= FIELD_DOF_COUNT) &
         CALL ERROR_ABORT('Reduced field array size does not match FIELD_DOF_COUNT.')

      REDUCED_VALUES = 0.d0
      DO NODE = 0, NNODES-1
         CALL MAP_FIELD_NODE(NODE, FIELD_DOF)
         REDUCED_VALUES(FIELD_DOF) = REDUCED_VALUES(FIELD_DOF) + FULL_VALUES(NODE)
      END DO

   END SUBROUTINE REDUCE_FIELD_ARRAY


   SUBROUTINE EXPAND_FIELD_ARRAY(REDUCED_VALUES, FULL_VALUES)

      REAL(KIND=8), DIMENSION(0:), INTENT(IN) :: REDUCED_VALUES
      REAL(KIND=8), DIMENSION(0:), INTENT(OUT) :: FULL_VALUES
      INTEGER :: NODE, FIELD_DOF

      IF (SIZE(REDUCED_VALUES) /= FIELD_DOF_COUNT) &
         CALL ERROR_ABORT('Reduced field array size does not match FIELD_DOF_COUNT.')
      IF (SIZE(FULL_VALUES) /= NNODES) &
         CALL ERROR_ABORT('Full field array size does not match NNODES.')

      DO NODE = 0, NNODES-1
         CALL MAP_FIELD_NODE(NODE, FIELD_DOF)
         FULL_VALUES(NODE) = REDUCED_VALUES(FIELD_DOF)
      END DO

   END SUBROUTINE EXPAND_FIELD_ARRAY

END MODULE field_dof_utils
