! Copyright (C) 2025 von Karman Institute for Fluid Dynamics (VKI)
!
! This file is part of PANTERA PIC-DSMC.
! It is distributed under the GNU General Public License, version 3 or later.

MODULE periodic_mesh_utils

   USE, INTRINSIC :: ieee_arithmetic, ONLY: ieee_is_finite

   IMPLICIT NONE
   PRIVATE

   INTEGER, PARAMETER, PUBLIC :: PERIODIC_MESH_OK = 0
   INTEGER, PARAMETER, PUBLIC :: PERIODIC_MESH_INVALID_INPUT = 1
   INTEGER, PARAMETER, PUBLIC :: PERIODIC_MESH_NO_MATCH = 2
   INTEGER, PARAMETER, PUBLIC :: PERIODIC_MESH_AMBIGUOUS = 3

   PUBLIC :: MATCH_PERIODIC_TRIANGLE

CONTAINS

   SUBROUTINE MATCH_PERIODIC_TRIANGLE(MASTER_COORDS, SLAVE_COORDS, TRANSLATION, TOLERANCE, &
                                      VERTEX_PERMUTATION, ERROR_CODE)

      IMPLICIT NONE

      REAL(KIND=8), DIMENSION(3,3), INTENT(IN) :: MASTER_COORDS, SLAVE_COORDS
      REAL(KIND=8), DIMENSION(3), INTENT(IN) :: TRANSLATION
      REAL(KIND=8), INTENT(IN) :: TOLERANCE
      INTEGER, DIMENSION(3), INTENT(OUT) :: VERTEX_PERMUTATION
      INTEGER, INTENT(OUT) :: ERROR_CODE

      LOGICAL, DIMENSION(3) :: USED_SLAVE_VERTEX
      INTEGER :: MASTER_VERTEX, SLAVE_VERTEX, MATCH_COUNT, MATCHED_VERTEX
      REAL(KIND=8), DIMENSION(3) :: EXPECTED_COORDS

      VERTEX_PERMUTATION = 0
      ERROR_CODE = PERIODIC_MESH_INVALID_INPUT

      IF (.NOT. ALL(IEEE_IS_FINITE(MASTER_COORDS)) .OR. &
          .NOT. ALL(IEEE_IS_FINITE(SLAVE_COORDS)) .OR. &
          .NOT. ALL(IEEE_IS_FINITE(TRANSLATION)) .OR. &
          .NOT. IEEE_IS_FINITE(TOLERANCE) .OR. TOLERANCE <= 0.d0) RETURN

      IF (NORM2(TRANSLATION) <= TOLERANCE) RETURN

      USED_SLAVE_VERTEX = .FALSE.
      DO MASTER_VERTEX = 1, 3
         EXPECTED_COORDS = MASTER_COORDS(:,MASTER_VERTEX) + TRANSLATION
         MATCH_COUNT = 0
         MATCHED_VERTEX = 0

         DO SLAVE_VERTEX = 1, 3
            IF (NORM2(SLAVE_COORDS(:,SLAVE_VERTEX) - EXPECTED_COORDS) <= TOLERANCE) THEN
               MATCH_COUNT = MATCH_COUNT + 1
               MATCHED_VERTEX = SLAVE_VERTEX
            END IF
         END DO

         IF (MATCH_COUNT == 0) THEN
            ERROR_CODE = PERIODIC_MESH_NO_MATCH
            RETURN
         ELSE IF (MATCH_COUNT > 1) THEN
            ERROR_CODE = PERIODIC_MESH_AMBIGUOUS
            RETURN
         END IF

         IF (USED_SLAVE_VERTEX(MATCHED_VERTEX)) THEN
            ERROR_CODE = PERIODIC_MESH_AMBIGUOUS
            RETURN
         END IF

         VERTEX_PERMUTATION(MASTER_VERTEX) = MATCHED_VERTEX
         USED_SLAVE_VERTEX(MATCHED_VERTEX) = .TRUE.
      END DO

      ERROR_CODE = PERIODIC_MESH_OK

   END SUBROUTINE MATCH_PERIODIC_TRIANGLE

END MODULE periodic_mesh_utils
